id: P9D6228A8
initial_creation_type: input
source_metadata:
  title: Guru Yoga Series
  language: pt
  description: 'A series of Guru Yoga (bla ma''i rnal ''byor) practices:'
  volume:
    d050988d271046c0a809e4c6fef541fc:
      title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord
        Atiśa'
      parent: Atiśa Dīpaṃkara
    6ebffdddfdd341c1b812161e7fc39076:
      title: Guru Yoga of the Guru Mahāmuni
      parent: Buddha Śākyamuni
    1d6f7dc6266d42288424b462c31d2735:
      title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless
        Teacher of All, Including the Devas'
      parent: Buddha Śākyamuni
    83b72780b264453c8c2541d375a0d4e1:
      title: A Profound and Concise Guru Yoga
      parent: Chatral Rinpoche
    660aa81f62ba43298f88c83c7664eac8:
      title: The Guru Yoga of the Profound Path
      parent: Dorje Tötreng Tsal
    884eb6ff0cb34bfbbb31684bbf212c44:
      title: 'The Gathering of Blessings: A Guru Yoga'
      parent: Dzogchen
    872d5e194c4b4806b04a26b923650cac:
      title: 'Guru Yoga: The Consummate Blessing'
      parent: Dzogchen
    1f2e8d781e524731998920e7698bec5a:
      title: Guru Yoga
      parent: Padmasambhava
    1896d93787b0408d82e2b242997d4397:
      title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
      parent: Gampopa Sonam Rinchen
    a4a5c4ff5335426aba37e8f84dc158f4:
      title: Guru Sādhana of Garab Dorje
      parent: Garab Dorje
    51563a8454a34da7b92b312b1b3de10c:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      parent: Garab Dorje
    9a99fd0d1d2e431688f2523b445c5c3b:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Gesar
    eae013ea843143e0ae401c0c7629fc27:
      title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
      parent: Haribhadra
    e3e3223a11d649059698c46dd403914b:
      title: Guru Yoga – A Rang Rig Ma Chö
      parent: Jamyang Khyentse Chökyi Lodrö
    7e3cc9dd01ab41c89bfc3edb60eb48ae:
      title: Letter of Advice to Jamyang Gyaltsen
      parent: Jamyang Khyentse Chökyi Lodrö
    9074c834c8004fe5ae6bcb7878c1f566:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Jamyang Khyentse Chökyi Lodrö
    804b304bbe00405b9389634d16e590c1:
      title: 'Drop of Wisdom Nectar: A Guru Yoga'
      parent: Jamyang Khyentse Chökyi Lodrö
    a16ce40b21824296b78a086ce13ef495:
      title: Guru Padma Yoga
      parent: Jamyang Khyentse Chökyi Lodrö
    f6e3744bfff74f44b902c38bf7f5a670:
      title: 'The Bright Lamp of Wisdom: A Guide to the Practice of Guru Yoga (Yeshe
        Saldrön)'
      parent: Jamyang Khyentse Chökyi Lodrö
    bd9ef978dd9f4671bcc49f4485dfadd0:
      title: 'The Bright Lamp of the Heart Essence (Nyingtik Saldrön): A Guru Yoga'
      parent: Jamyang Khyentse Chökyi Lodrö
    5f1468da76b94f3d89e9db985ec025df:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Jigme Lingpa
    b5743b5fbd9041a2b0ced697fc4fcc02:
      title: 'The Swift Bestowal of Blessings: A Guru Yoga'
      parent: Khenchen Jigme Phuntsok
    4d92ef583938413e83b82058e0740ea3:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Kurukullā
    8194ea6c2d574cc882d550e8fdf7bfbf:
      title: Guru Yoga of Jetsün Lochen, Queen of Yoginīs
      parent: Lochen Chönyi Zangmo
    bf01d3a86b0842e79135da65e2a20929:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Longchen Rabjam
    b5fe960e8197476ebb00bdc0a79a9de1:
      title: 'Guru Yoga: The Complete Path of Sūtra And Tantra'
      parent: Mañjuśrī
    7c98d04bd71c41a997cf63332f8e6b75:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      parent: Marpa, Milarepa & Gampopa
    2105580e1ead46ec84e569285519c79d:
      title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
      parent: Marpa, Milarepa & Gampopa
    ba3a6827715b445e8e8091e2e3ef74ab:
      title: Guru Yoga of Lord Marpa Lotsāwa
      parent: Marpa Chökyi Lodrö
    db215d56545d4f5a80e10fcaa960132a:
      title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
      parent: Marpa Chökyi Lodrö
    338f9aeb6cdf4f81a085b1dfbfa5ed2c:
      title: Guru Yoga of Jetsün Shepa Dorje
      parent: Milarepa
    b494407e9c9846d8945e3a41ef112b34:
      title: 'A Drop of Moonlight: A Guru Yoga for Lord Mila'
      parent: Milarepa
    0745c695e6984ad3807959fb18776978:
      title: Supplication to Lord Mila Shepa Dorje
      parent: Milarepa
    8287a6d3183e470085983a7779c6f0eb:
      title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
      parent: Milarepa
    344807e890634ef69f07bb54d9432c0d:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Mipham Rinpoche
    992b8ead3f604eddb8cdc2f61249ba58:
      title: 'The Radiant Treasure of Blessings: A Guru Yoga of the Great Vajradhara
        Ngawang Samten Lodrö'
      parent: Ngawang Samten Lodrö
    2453c515cf2a44ba995313ac73f87823:
      title: A Concise Guru Yoga
      parent: Padmasambhava
    bf5ea166eec54df3b928643a7430b129:
      title: 'The Quintessence of the Profound Path: A Concise Guide to the Stages
        of Visualization for the Guru Yoga of the Seven-Line Supplication, A Shower
        of Blessings'
      parent: Padmasambhava
    ace4e6204db044e0986c182b5e2a0e06:
      title: 'The Swift Infusion of Blessings: A Prayer and Aspiration for the Stages
        of the Path Combined with Guru Yoga'
      parent: Padmasambhava
    54fb4a901ef0424e8240ccc6276d4538:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Padmasambhava
    29c3414036574a43affe22a2aded2bbc:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      parent: Padmasambhava
    f6bfef7b1cad45079ed25a296f303f1e:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Padmasambhava
    dcfb98ad5e5d4b7b8a6841f79174981b:
      title: Guru Yoga of the Great Tertön Pema Lingpa
      parent: Pema Lingpa
    fe89da5c54024ba1b6ff22e40becd072:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      parent: Rongzom Chökyi Zangpo
    aed4a22913ae4af59b157ba31369080b:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Sakya Paṇḍita
    6456c52c09294d1ba5dc55f6ea3dc41a:
      title: A Guru Yoga of Śavari
      parent: Śavari
    7458f625095443fea08950aef96c2c10:
      title: 'The Profound Path of Guru Yoga: A Way to Freedom for the Fortunate'
      parent: Sera Khandro
    10a7583ba72b420dac935f1f14747984:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Smṛtijñānakīrti
    c310a75de4cf46ceabbb90aac3683153:
      title: 'Self-Arising Wisdom: Songtsen Gampo Guru Sādhana'
      parent: Songtsen Gampo
    43bc5339cee34d3ab00af11374181b77:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Three Deities of Long Life
    dd243141dbdd4def8d126cc49f7ce78f:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Three Mañjughoṣas
    fbaa5003736445ca9195a1a791e32ffa:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Trulshik Rinpoche
    1f7d181cda3246e59233540809808e45:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Tsongkhapa Lobzang Drakpa
    fcff779bf5db450ca0bd847508773dff:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Vajrasattva
created_at: '2022-03-01T03:55:16.214894'
last_modified_at: '2022-03-01T03:55:16.214897'
